#-------------------------------
# General Site Settings

menu:
- {name: 'Projets', url: ''}
- {name: 'À propos',    url: 'about'}
- {name: 'Mon CV',    url: 'file:///home/baptiste/T%C3%A9l%C3%A9chargements/BaptisteCVLatex.pdf'}
- {name: 'Blog',     url: 'blog'}
- {name: 'Contact',  url: 'contact'}

#-------------------------------
# Projects Section

projects:
- {name: 'Projet 1',   url: 'proj-1'}
- {name: 'Projet 2',   url: 'proj-2'}


#-------------------------------
# Contact Section

social:
- {icon: 'github',    link: 'https://github.com/baptiste-bedouret'}
- {icon: 'linkedin',  link: 'https://www.linkedin.com/in/baptiste-bedouret/'}
- {icon: 'envelope',  link: 'mailto:mailto:b.bedouret@gmail.com'}

# social network icons available:  / 'github' / 'linkedin' /

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'Personal portfolio powered by Jekyll and GitHub Pages '
  rel-author: 'https://plus.google.com/u/0/#'
  rel-publisher: 'https://plus.google.com/u/0/#'

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-analytics-ua: 'UA-112060364-3'

#-------------------------------
# Disqus Section

# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: ''
