#-------------------------------
# General Site Settings

menu:
- {name: 'Projets', url: ''}
- {name: 'À propos',    url: 'about'}
- {name: 'Mon CV',    url: 'pages/CV-Baptiste_Bédouret.pdf'}
- {name: 'Blog',     url: 'blog'}

#-------------------------------
# Projects Section

projects:
- {name: 'Projet 1',   url: 'proj-1'}
- {name: 'Projet 2',   url: 'proj-2'}
- {name: 'Projet 3',   url: 'proj-3'}
- {name: 'Projet 4',   url: 'proj-4'}
- {name: 'Projet 5',   url: 'proj-5'}
- {name: 'Projet 6',   url: 'proj-6'}
- {name: 'Projet 7',   url: 'proj-7'}
- {name: 'Projet 8',   url: 'proj-8'}
- {name: 'Projet 9',   url: 'proj-9'}
- {name: 'Projet 10',   url: 'proj-10'}
- {name: 'Projet 11',   url: 'proj-11'}

#-------------------------------
# Contact Section

social:
- {icon: 'github',    link: 'https://github.com/baptiste-bedouret'}
- {icon: 'linkedin',  link: 'https://www.linkedin.com/in/baptiste-bedouret/'}
- {icon: 'envelope',  link: 'mailto:mailto:b.bedouret@gmail.com'}
- {icon: 'phone',  link: 'tel:+33783357995'}

# social network icons available:  / 'github' / 'linkedin' / phone 

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'Personal portfolio powered by Jekyll and GitHub Pages '
  rel-author: 'https://plus.google.com/u/0/#'
  rel-publisher: 'https://plus.google.com/u/0/#'

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-analytics-ua: 'UA-112060364-3'

#-------------------------------
# Disqus Section

# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: ''
